"""massage

Revision ID: 62ec0b59a65b
Revises: 3234a7a6286f
Create Date: 2026-04-16 13:20:19.938485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62ec0b59a65b'
down_revision: Union[str, None] = '3234a7a6286f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('habr', 'views')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habr', sa.Column('views', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
